In [1]:
import tensorflow as tf

2024-11-27 10:07:08.655572: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1732720028.667147 2499595 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732720028.670690 2499595 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-27 10:07:08.683420: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [19]:
# Sample text data
texts = ["This is the first sentence.", "This is the second sentence with something else."]
labels = [0, 1]  # Example labels

# Tokenize the text
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

# Pad sequences to the same length
max_length = max(len(seq) for seq in sequences)
padded_sequences = tf.keras.preprocessing.sequence.pad_sequences(sequences, maxlen=max_length)

# Create a TensorFlow dataset
dataset = tf.data.Dataset.from_tensor_slices((padded_sequences, labels))

# Optional: Batch and shuffle the dataset
dataset = dataset.batch(32).shuffle(buffer_size=len(dataset))

(<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[0, 0, 0, 1, 2, 3, 5, 4],
       [1, 2, 3, 6, 4, 7, 8, 9]], dtype=int32)>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>)


In [25]:
tokenizer.word_index

{'this': 1,
 'is': 2,
 'the': 3,
 'sentence': 4,
 'first': 5,
 'second': 6,
 'with': 7,
 'something': 8,
 'else': 9}

In [21]:
padded_sequences

array([[0, 0, 0, 1, 2, 3, 5, 4],
       [1, 2, 3, 6, 4, 7, 8, 9]], dtype=int32)

In [6]:
# Example data
sentences = [
    "This is the first sentence.",
    "Here is another one.",
    "TensorFlow datasets are powerful.",
    "Data preparation is important.",
]
labels = [0, 1, 0, 1] 

In [7]:
raw_dataset = tf.data.Dataset.from_tensor_slices((sentences, labels))

In [12]:
for sentence, label in raw_dataset:
    print(sentence, label)

tf.Tensor(b'This is the first sentence.', shape=(), dtype=string) tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(b'Here is another one.', shape=(), dtype=string) tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(b'TensorFlow datasets are powerful.', shape=(), dtype=string) tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(b'Data preparation is important.', shape=(), dtype=string) tf.Tensor(1, shape=(), dtype=int32)


In [13]:
tokens = tf.strings.split(sentence)

In [15]:
tokens.to_tensor()

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'to_tensor'

In [16]:
 padded_tokens = tf.concat([tokens, tf.constant([""] * (6 - tf.shape(tokens)[0]))], axis=0)[:6]

TypeError: Cannot convert [''] to EagerTensor of dtype int32

In [9]:
# Step 2: Preprocessing function with padding
def preprocess(sentence, label):
    # Tokenize sentences into words
    tokens = tf.strings.split(sentence)
    # Convert RaggedTensor to a dense tensor with padding
    padded_tokens = tokens.to_tensor(default_value="", shape=(6,))  # Pad or truncate to length 6
    return padded_tokens, label

# Apply preprocessing
processed_dataset = raw_dataset.map(preprocess)

AttributeError: in user code:

    File "/tmp/ipykernel_2499595/1869861865.py", line 6, in preprocess  *
        padded_tokens = tokens.to_tensor(default_value="", shape=(6,))  # Pad or truncate to length 6

    AttributeError: 'SymbolicTensor' object has no attribute 'to_tensor'


In [4]:
# Example data
sentences = [
    "This is the first sentence.",
    "Here is another one.",
    "TensorFlow datasets are powerful.",
    "Data preparation is important.",
]
labels = [0, 1, 0, 1]  # Binary labels for simplicity

# Step 1: Create a TensorFlow Dataset
raw_dataset = tf.data.Dataset.from_tensor_slices((sentences, labels))

# Step 2: Preprocessing function with padding
def preprocess(sentence, label):
    # Tokenize sentences into words
    tokens = tf.strings.split(sentence)
    # Convert RaggedTensor to a dense tensor with padding
    padded_tokens = tokens.to_tensor(default_value="", shape=(6,))  # Pad or truncate to length 6
    return padded_tokens, label

# Apply preprocessing
processed_dataset = raw_dataset.map(preprocess)

# Step 3: Batch the data
batch_size = 2
batched_dataset = processed_dataset.batch(batch_size)

# Step 4: Shuffle and prefetch
final_dataset = batched_dataset.shuffle(buffer_size=100).prefetch(buffer_size=tf.data.AUTOTUNE)

# Inspect the dataset
for tokens, lbl in final_dataset.take(1):
    print("Tokens:", tokens.numpy())
    print("Labels:", lbl.numpy())


AttributeError: in user code:

    File "/tmp/ipykernel_2499595/3407354333.py", line 18, in preprocess  *
        padded_tokens = tokens.to_tensor(default_value="", shape=(6,))  # Pad or truncate to length 6

    AttributeError: 'SymbolicTensor' object has no attribute 'to_tensor'
